# Generated by Django 5.0.3 on 2024-03-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EncryptionSystem_Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciphertext',
            name='cpht_type',
            field=models.CharField(default='', max_length=255, verbose_name='文件类型'),
            preserve_default=False,
        ),
    ]
