# Generated by Django 5.0.3 on 2024-03-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EncryptionSystem_Main', '0002_ciphertext_cpht_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('pk_id', models.UUIDField(primary_key=True, serialize=False, verbose_name='公钥id')),
                ('pk_userid', models.UUIDField(verbose_name='用户id')),
                ('pk_create_time', models.DateTimeField(auto_now_add=True, verbose_name='公钥创建时间')),
                ('pk_text', models.CharField(max_length=255, null=True, verbose_name='公钥文本')),
            ],
        ),
    ]
