# Generated by Django 5.0.3 on 2024-03-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EncryptionSystem_Main', '0003_publickey'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkrecord',
            name='kfile_id',
            field=models.UUIDField(default=0, verbose_name='密钥id'),
        ),
    ]
