# Generated by Django 5.0.3 on 2024-03-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EncryptionSystem_Main', '0004_checkrecord_kfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfile',
            name='kfile_key',
            field=models.CharField(default='', max_length=2048, verbose_name='密钥文本'),
        ),
        migrations.AlterField(
            model_name='privatekeycpht',
            name='pkc_cpht',
            field=models.CharField(max_length=2048, null=True, verbose_name='私钥密文'),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='pk_text',
            field=models.CharField(max_length=2048, null=True, verbose_name='公钥文本'),
        ),
    ]
